-- CreateTable
CREATE TABLE "OwidCovidLatest" (
    "iso_code" TEXT NOT NULL,
    "continent" TEXT NOT NULL DEFAULT E'',
    "location" TEXT NOT NULL,
    "date" TEXT NOT NULL,
    "total_cases" INTEGER NOT NULL DEFAULT 0,
    "new_cases" INTEGER NOT NULL DEFAULT 0,
    "new_cases_smoothed" REAL NOT NULL DEFAULT 0,
    "total_deaths" INTEGER NOT NULL DEFAULT 0,
    "new_deaths" INTEGER NOT NULL DEFAULT 0,
    "new_deaths_smoothed" REAL NOT NULL DEFAULT 0,
    "total_cases_per_million" REAL NOT NULL DEFAULT 0,
    "new_cases_per_million" REAL NOT NULL DEFAULT 0,
    "new_cases_smoothed_per_million" REAL NOT NULL DEFAULT 0,
    "total_deaths_per_million" REAL NOT NULL DEFAULT 0,
    "new_deaths_per_million" REAL NOT NULL DEFAULT 0,
    "new_deaths_smoothed_per_million" REAL NOT NULL DEFAULT 0,
    "reproduction_rate" REAL NOT NULL DEFAULT 0,
    "icu_patients" INTEGER NOT NULL DEFAULT 0,
    "icu_patients_per_million" REAL NOT NULL DEFAULT 0,
    "hosp_patients" INTEGER NOT NULL DEFAULT 0,
    "hosp_patients_per_million" REAL NOT NULL DEFAULT 0,
    "weekly_icu_admissions" INTEGER NOT NULL DEFAULT 0,
    "weekly_icu_admissions_per_million" REAL NOT NULL DEFAULT 0,
    "weekly_hosp_admissions" INTEGER NOT NULL DEFAULT 0,
    "weekly_hosp_admissions_per_million" REAL NOT NULL DEFAULT 0,
    "total_tests" BIGINT NOT NULL DEFAULT 0,
    "new_tests" BIGINT NOT NULL DEFAULT 0,
    "total_tests_per_thousand" REAL NOT NULL DEFAULT 0,
    "new_tests_per_thousand" REAL NOT NULL DEFAULT 0,
    "new_tests_smoothed" BIGINT NOT NULL DEFAULT 0,
    "new_tests_smoothed_per_thousand" REAL NOT NULL DEFAULT 0,
    "positive_rate" REAL NOT NULL DEFAULT 0,
    "tests_per_case" REAL NOT NULL DEFAULT 0,
    "tests_units" TEXT NOT NULL DEFAULT E'',
    "total_vaccinations" BIGINT NOT NULL DEFAULT 0,
    "people_vaccinated" BIGINT NOT NULL DEFAULT 0,
    "people_fully_vaccinated" BIGINT NOT NULL DEFAULT 0,
    "total_boosters" BIGINT NOT NULL DEFAULT 0,
    "new_vaccinations" INTEGER NOT NULL DEFAULT 0,
    "new_vaccinations_smoothed" INTEGER NOT NULL DEFAULT 0,
    "total_vaccinations_per_hundred" REAL NOT NULL DEFAULT 0,
    "people_vaccinated_per_hundred" REAL NOT NULL DEFAULT 0,
    "people_fully_vaccinated_per_hundred" REAL NOT NULL DEFAULT 0,
    "total_boosters_per_hundred" REAL NOT NULL DEFAULT 0,
    "new_vaccinations_smoothed_per_million" INTEGER NOT NULL DEFAULT 0,
    "new_people_vaccinated_smoothed" INTEGER NOT NULL DEFAULT 0,
    "new_people_vaccinated_smoothed_per_hundred" REAL NOT NULL DEFAULT 0,
    "stringency_index" REAL NOT NULL DEFAULT 0,
    "population" BIGINT NOT NULL DEFAULT 0,
    "population_density" REAL NOT NULL DEFAULT 0,
    "median_age" REAL NOT NULL DEFAULT 0,
    "aged_65_older" REAL NOT NULL DEFAULT 0,
    "aged_70_older" REAL NOT NULL DEFAULT 0,
    "gdp_per_capita" REAL NOT NULL DEFAULT 0,
    "extreme_poverty" REAL NOT NULL DEFAULT 0,
    "cardiovasc_death_rate" REAL NOT NULL DEFAULT 0,
    "diabetes_prevalence" REAL NOT NULL DEFAULT 0,
    "female_smokers" REAL NOT NULL DEFAULT 0,
    "male_smokers" REAL NOT NULL DEFAULT 0,
    "handwashing_facilities" REAL NOT NULL DEFAULT 0,
    "hospital_beds_per_thousand" REAL NOT NULL DEFAULT 0,
    "life_expectancy" REAL NOT NULL DEFAULT 0,
    "human_development_index" REAL NOT NULL DEFAULT 0,
    "excess_mortality_cumulative_absolute" REAL NOT NULL DEFAULT 0,
    "excess_mortality_cumulative" REAL NOT NULL DEFAULT 0,
    "excess_mortality" REAL NOT NULL DEFAULT 0,
    "excess_mortality_cumulative_per_million" REAL NOT NULL DEFAULT 0
);

-- CreateIndex
CREATE UNIQUE INDEX "OwidCovidLatest_iso_code_date_key" ON "OwidCovidLatest"("iso_code", "date");
